Updated build scripts with changes from upstream heroku * added back php-min * optimized composer build * cleaned out docs from builds * bumped default versions * added php 7.1 and 7.2 support * added gettext-runtime which should be all thats required for php, and much faster to compile

diff --git a/recipes/composer b/recipes/composer
--- a/recipes/composer
+++ b/recipes/composer
@@ -9,16 +9,25 @@ set -o pipefail
 # fail harder
 set -eux
 
-DEFAULT_VERSION="1.2.0"
+DEFAULT_VERSION="1.6.5"
 dep_version=${VERSION:-$DEFAULT_VERSION}
 
 echo "-----> Bundling Composer (${dep_version})..."
 
-buildcurl php 5.6.14 | tar xz -C $OUT_PREFIX
+buildcurl php-min 7.0.27 | tar xz -C $OUT_PREFIX
 
 export PATH=${OUT_PREFIX}/bin:$PATH
 
-curl -sS https://getcomposer.org/installer | php -- \
+EXPECTED_SIGNATURE=$(wget -q -O - https://composer.github.io/installer.sig)
+php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")
+if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then
+	>&2 echo 'ERROR: Invalid installer signature'
+	rm composer-setup.php
+	exit 1
+fi
+
+php composer-setup.php \
   --version=${dep_version} \
   --filename=composer \
   --install-dir=${OUT_PREFIX}/bin
